<h1>会員登録</h1>

<?php
  $form->setAttribute('action', $this->url('member', array('action' => 'confirm')));
  $form->prepare();
?>

<p><?php echo $this->form()->openTag($form); ?></p>
<p><?php echo $this->formHidden($form->get('id')); ?></p>
<p><?php echo $this->formRow($form->get('login_id')); ?></p>
<p><?php echo $this->formRow($form->get('password')); ?></p>
<p><?php echo $this->formRow($form->get('password_confirmation')); ?></p>
<p><?php echo $this->formRow($form->get('name')); ?></p>
<p><?php echo $this->formRow($form->get('name_kana')); ?></p>
<p><?php echo $this->formRow($form->get('mail_address')); ?></p>
<p><?php echo $this->formRow($form->get('birthday')); ?></p>
<p><?php echo $this->formRow($form->get('business_classification_id')->setAttribute('options', $bc_ary)); ?></p>
<p><?php echo $this->formSubmit($form->get('submit')); ?></p>
<p><?php echo $this->form()->closeTag(); ?></p>
