<h1>会員登録確認</h1>

<?php
$form->setAttribute('action', $this->url('member', array('action' => 'add')));
$form->prepare();
?>

<p>ログインID : <?php echo $postData["login_id"]; ?></p>
<p>氏名:<?php echo $postData["name"]; ?></p>
<p>氏名（かな）:<?php echo $postData["name_kana"]; ?></p>
<p>メールアドレス:<?php echo $postData["mail_address"]; ?></p>
<p>生年月日:<?php echo $postData["birthday"]; ?></p>
<p>業種:<?php echo $business_classification->name; ?></p>

<p><?php echo $this->form()->openTag($form); ?></p>
<p><?php echo $this->formHidden($form->get('id')); ?></p>
<p><?php echo $this->formHidden($form->get('login_id')); ?></p>
<p><?php echo $this->formHidden($form->get('password')); ?></p>
<p><?php echo $this->formHidden($form->get('password_confirmation')); ?></p>
<p><?php echo $this->formHidden($form->get('name')); ?></p>
<p><?php echo $this->formHidden($form->get('name_kana')); ?></p>
<p><?php echo $this->formHidden($form->get('mail_address')); ?></p>
<p><?php echo $this->formHidden($form->get('birthday')); ?></p>
<p><?php echo $this->formSubmit($form->get('submit')); ?></p>
<p><?php echo $this->form()->closeTag(); ?></p>
<a href="<?php echo $this->url('member', array('action' => 'add')) ?>">修正する</a>

<?php /*
<p>
<?php echo $this->formRow($form->get('business_classification_id')->setAttribute('options', $bc_ary)); ?>
</p>
*/
?>
