<h1>会員登録確認</h1>

<p>ログインID : <?php echo $postData["login_id"]; ?></p>
<p>氏名:<?php echo $postData["name"]; ?></p>
<p>氏名（かな）:<?php echo $postData["name_kana"]; ?></p>
<p>メールアドレス:<?php echo $postData["mail_address"]; ?></p>
<p>生年月日:<?php echo $postData["birthday"]; ?></p>
<p>業種:<?php echo $business_classification->name; ?></p>

<form method="POST" name="member" action="/member/complete" id="member">

    <?php
    foreach($postData as $key => $value) {
      echo "<input type='hidden' name=$key value=$value>";
    }
    ?>

    <p>
        <button class="submit" data-action="/member/add">戻る</button>
        <button class="submit" data-action="/member/complete">登録</button>
    </p>

</form>

<script>
    $('.submit').click(function() {
      $(this).parents('form').attr('action', $(this).data('action'));
      $(this).parents('form').submit();
    });
</script>
