 <?php
 // module/Member/view/member/member/index.phtml:

 $title = 'My members';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('member', array('action'=>'add'));?>">Add new member</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($members as $member) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($member->title);?></td>
     <td><?php echo $this->escapeHtml($member->artist);?></td>
     <td>
         <a href="<?php echo $this->url('member',
             array('action'=>'edit', 'id' => $member->id));?>">Edit</a>
         <a href="<?php echo $this->url('member',
             array('action'=>'delete', 'id' => $member->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
